// <auto-generated />
using System;
using ArtBack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtBack.Infrastructure.Migrations
{
    [DbContext(typeof(ArtDbContext))]
    [Migration("20251212153819_Initial fixed")]
    partial class Initialfixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ArtBack.Domain.Entities.Artwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ArtworkCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.CartArtwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ArtworkCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CartId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("CartId");

                    b.ToTable("CartArtworks");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ArtType")
                        .HasColumnType("int");

                    b.Property<int>("ColorPalette")
                        .HasColumnType("int");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.Property<int>("Technique")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.DiscountCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BeginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("double");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("DiscountCoupons");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.LikedArtwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("ClientId");

                    b.ToTable("LikedArtworks");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("AppliedDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DiscountCouponId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DiscountCouponId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.OrderArtwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ArtworkCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderArtworks");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("ArtBack.Domain.Entities.User");

                    b.Property<int>("OrderedArtworkCount")
                        .HasColumnType("int");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Vendor", b =>
                {
                    b.HasBaseType("ArtBack.Domain.Entities.User");

                    b.Property<int>("ArtworkCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Profits")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SoldArtworkCount")
                        .HasColumnType("int");

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Artwork", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.Category", "Category")
                        .WithOne("Artwork")
                        .HasForeignKey("ArtBack.Domain.Entities.Artwork", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtBack.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Artworks")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Cart", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.Client", "Client")
                        .WithOne("Cart")
                        .HasForeignKey("ArtBack.Domain.Entities.Cart", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.CartArtwork", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.Artwork", "Artwork")
                        .WithMany("CartArtwork")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtBack.Domain.Entities.Cart", "Cart")
                        .WithMany("CartArtwork")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.LikedArtwork", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.Artwork", "Artwork")
                        .WithMany("LikedArtworks")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtBack.Domain.Entities.Client", "Client")
                        .WithMany("LikedArtworks")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Order", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtBack.Domain.Entities.DiscountCoupon", "DiscountCoupon")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountCouponId");

                    b.Navigation("Client");

                    b.Navigation("DiscountCoupon");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.OrderArtwork", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.Artwork", "Artwork")
                        .WithMany("OrderArtwork")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtBack.Domain.Entities.Order", "Order")
                        .WithMany("OrderArtwork")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Client", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("ArtBack.Domain.Entities.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("ArtBack.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("ArtBack.Domain.Entities.Vendor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Artwork", b =>
                {
                    b.Navigation("CartArtwork");

                    b.Navigation("LikedArtworks");

                    b.Navigation("OrderArtwork");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartArtwork");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Category", b =>
                {
                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.DiscountCoupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderArtwork");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Client", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("LikedArtworks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ArtBack.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
